# Generated by Django 2.2.6 on 2019-10-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=100)),
                ('transport_name_plural', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=100)),
                ('status_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=100)),
                ('schedule_id', models.CharField(max_length=100)),
                ('transport_id', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100, null=True)),
                ('transport_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.TransportDetail')),
            ],
        ),
    ]
