# Generated by Django 2.2.6 on 2019-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=100)),
                ('schedule_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transport_id', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopDetail',
            fields=[
                ('area_name', models.CharField(max_length=100, null=True)),
                ('direction_name', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=100)),
                ('stop_detail_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('map_icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=100)),
                ('status_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=100)),
                ('transport_name_plural', models.CharField(max_length=100)),
                ('schedules', models.ManyToManyField(to='bot.ScheduleDetail')),
            ],
        ),
        migrations.CreateModel(
            name='TrackDetail',
            fields=[
                ('direction', models.IntegerField()),
                ('track_detail_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_hidden', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('shape', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('stops', models.ManyToManyField(to='bot.StopDetail')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledetail',
            name='tracks',
            field=models.ManyToManyField(to='bot.TrackDetail'),
        ),
    ]
