# Generated by Django 2.2.6 on 2019-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopDetail',
            fields=[
                ('area_name', models.CharField(max_length=100)),
                ('direction_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('stop_detail_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('map_icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheduledetail',
            name='schedule_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TrackDetail',
            fields=[
                ('direction', models.IntegerField()),
                ('track_detail_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_hidden', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('shape', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('stops', models.ManyToManyField(to='bot.StopDetail')),
            ],
        ),
    ]
